site_name: dython
repo_name: shakedzy/dython
repo_url: https://github.com/shakedzy/dython
theme:
  name: material
  palette:
    primary: light blue
    accent: blue
  logo: images/favicon.png
  favicon: images/favicon.png
nav:
  - Home: 'index.md'
  - Getting Started:
    - Installation: 'getting_started/installation.md'
    - Examples: 'getting_started/examples.md'
  - Modules:
    - nominal: 'modules/nominal.md'
    - model_utils: 'modules/model_utils.md'
    - sampling: 'modules/sampling.md'
  - Related Blogosts:
    - The Search for Categorical Correlation: "https://medium.com/@shakedzy/the-search-for-categorical-correlation-a1cf7f1888c9"
    - Hard ROC - Really Understanding & Properly Using ROC and AUC: https://medium.com/@shakedzy/hard-roc-really-understanding-and-properly-using-roc-and-auc-13413cf0dc24"
google_analytics:
  - UA-141245946-2
  - auto
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
plugins:
  - search