site_name: dython
repo_name: shakedzy/dython
repo_url: https://github.com/shakedzy/dython
theme:
  name: material
  palette:
    primary: black
    accent: blue
  logo: images/favicon.png
  favicon: images/favicon.png
nav:
  - Home: 'index.md'
  - Modules:
    - nominal: 'nominal.md'
    - model_utils: 'model_utils.md'
    - sampling: 'sampling.md'
  - Examples: 'examples.md'
  - Related Blogosts:
    - The Search for Categorical Correlation: "https://medium.com/@shakedzy/the-search-for-categorical-correlation-a1cf7f1888c9"
    - Hard ROC - Really Understanding & Properly Using ROC and AUC: https://medium.com/@shakedzy/hard-roc-really-understanding-and-properly-using-roc-and-auc-13413cf0dc24"
google_analytics:
  - UA-141245946-2
  - auto